{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-httr2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/httr2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/httr2/httr2_{{ version }}.tar.gz
  sha256: 0f4a3f094117c8d1b37c67af70d702de25e0db5536079b5560673995931998d1

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.0.0
    - r-curl >=5.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-openssl
    - r-r6
    - r-rappdirs
    - r-rlang >=1.1.0
    - r-vctrs >=0.6.3
    - r-withr
  run:
    - r-base
    - r-cli >=3.0.0
    - r-curl >=5.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-openssl
    - r-r6
    - r-rappdirs
    - r-rlang >=1.1.0
    - r-vctrs >=0.6.3
    - r-withr

test:
  commands:
    - $R -e "library('httr2')"           # [not win]
    - "\"%R%\" -e \"library('httr2')\""  # [win]

about:
  home: https://httr2.r-lib.org
  dev_url: https://github.com/r-lib/httr2
  license: MIT
  summary: Tools for creating and modifying HTTP requests, then performing them and processing the results. 'httr2' is a modern re-imagining of 'httr' that uses a pipe-based interface and solves more of the problems that API wrapping packages face.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
