{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-httr2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/httr2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/httr2/httr2_{{ version }}.tar.gz
  sha256: 352032029512f28f6f440ace0078e859ad3945d6b20841963b372523b6974b3d

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-cli >=3.0.0
    - r-curl
    - r-glue
    - r-magrittr
    - r-openssl
    - r-rappdirs
    - r-rlang >=1.0.0
    - r-withr
  run:
    - r-base
    - r-r6
    - r-cli >=3.0.0
    - r-curl
    - r-glue
    - r-magrittr
    - r-openssl
    - r-rappdirs
    - r-rlang >=1.0.0
    - r-withr

test:
  commands:
    - $R -e "library('httr2')"           # [not win]
    - "\"%R%\" -e \"library('httr2')\""  # [win]

about:
  home: https://httr2.r-lib.org, https://github.com/r-lib/httr2
  license: MIT
  summary: Tools for creating and modifying HTTP requests, then performing them and processing the results. 'httr2' is a modern re-imagining of 'httr' that uses a pipe-based interface and solves more of the problems that API wrapping packages face.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
